### ISSUE TITLE
Add REAME.md 

### ISSUE THREAD

**Issue by DipanshKhandelwal** [sugarlabs/memorize-activity#12]
Adding README will allow everyone to get information about the project and help them run the project locally.

**Comment by lalitmee** [comment]
I can add README file to this project, but to do the same I need some documentation from which I can create a good README file.

**Comment by quozl** [comment]
There was certainly plenty of documentation available to do this, and a bare README.md was added in a25f3011c3adf5aad7f9d32c111608f142357be5, but as it missed much of the available documentation I've had another go at it and written a new one.

* 8f8ef55898ebe59d00ceec8ce0970ca048c3fe9a
* 75bd4c7f70ec8835b523168df1a571c438618c73
