### ISSUE TITLE
Redesign 5x5 tiles page

### ISSUE THREAD

**Issue by yashagrawal3** [sugarlabs/memorize-activity#17]
**Current :**
It looks like
![screenshot of memorize activity](https://user-images.githubusercontent.com/22298818/36629531-d96cf4d6-197c-11e8-944d-7fe124d67f03.png)

**Redesign :**

Add a black and inactive tile in the center of 5x5 tiles, this will give a bit more symmetrical look.

**Comment by Aniket21mathur** [comment]
No need to keep it open.
