### ISSUE TITLE
Fallback to espeak binary is broken

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/memorize-activity#3]
speak/espeak.py has code to try use GStreamer espeak module and if that fails then instead try use espeak binary.

...but with python GStreamer module is installed but GStreamer espeak module unavailable, Memorize fails to load.  Logfile hints that it is loaded via speak/voice.py _init_voice_cache loop (sorry, I have no easy access to the test machine so is writing from memory).

**Comment by godiard** [comment]
@jonassmedegaard, I can try solve this, but without the gstreameer espeak plugin, you loose the text to speech feature [1] in Sugar too.
Did you try package the plugin? Trisquel have a working package [2] 

[1] http://wiki.sugarlabs.org/go/Features/Global_Text_To_Speech
[2] http://mirror.fsf.org/trisquel/pool/main/g/gst-plugins-espeak/

**Comment by jonassmedegaard** [comment]
Quoting Gonzalo Odiard (2015-06-28 19:10:40)
> @jonassmedegaard, I can try solve this, but without the gstreameer espeak
> plugin, you loose the text to speech feature [1] in Sugar too.
> Did you try package the plugin? Trisquel have a working package [2]

Thanks for the warning.  Package gst-plugins-espeak already packaged for 
Debian, awaiting ftpmaster approval: 
https://ftp-master.debian.org/new/gst-plugins-espeak_0.4.0-1.html

I still find it relevant to fix this bug in Memorize - or simplify code 
to not try. :-)


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by godiard** [comment]
I agree about simplify code on Memorize, I will keep this issue opened.
