### ISSUE TITLE
Port speak/ to sugar3.speech

### ISSUE THREAD

**Issue by quozl** [sugarlabs/memorize-activity#8]
Memorize embeds a shim over gst-plugins-espeak, and this shim is now part of the toolkit, so port to using the toolkit.  [sugar3.speech](https://developer.sugarlabs.org/sugar3/sugar3.speech.html#module-sugar3.speech)

**Comment by mk1299** [comment]
Can I start working on this if no one else is?

**Comment by quozl** [comment]
Thanks for your interest.  @nswarup14 began working on this, see https://github.com/sugarlabs/memorize-activity/pull/20/commits/03461e05410667fe1b27afbe6ae5c7a09a609769 and the error in https://github.com/sugarlabs/memorize-activity/pull/20 that needs fixing; so you might base your work on theirs,

By the way; don't ask, just investigate and do it, see our [Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing) guide which says "_there is no need to ask permission to work on an issue. You should check for pull requests linked to an issue you are addressing; if there are none, then assume nobody has done anything. Begin to fix the problem, test, make your commits, push your commits, then make a pull request._".
